### ISSUE TITLE
AccountSetup.pwn

### ISSUE THREAD

**Issue by nicholasx5** [Sparke00/Diverse-Roleplay#3]
`C:\Users\PC\Desktop\Diverse-Roleplay-master\gamemodes\AccountSetup.pwn(4) : warning 235: public function lacks forward declaration (symbol "OnPlayerRequestClass")
C:\Users\PC\Desktop\Diverse-Roleplay-master\gamemodes\AccountSetup.pwn(6) : error 017: undefined symbol "SetPVarInt"
C:\Users\PC\Desktop\Diverse-Roleplay-master\gamemodes\AccountSetup.pwn(7) : error 017: undefined symbol "IsPlayerNPC"
C:\Users\PC\Desktop\Diverse-Roleplay-master\gamemodes\AccountSetup.pwn(10) : error 017: undefined symbol "GetNPCID"
C:\Users\PC\Desktop\Diverse-Roleplay-master\gamemodes\AccountSetup.pwn(11) : warning 217: loose indentation
C:\Users\PC\Desktop\Diverse-Roleplay-master\gamemodes\AccountSetup.pwn(12) : error 017: undefined symbol "NPCInfo"
C:\Users\PC\Desktop\Diverse-Roleplay-master\gamemodes\AccountSetup.pwn(12) : warning 215: expression has no effect
C:\Users\PC\Desktop\Diverse-Roleplay-master\gamemodes\AccountSetup.pwn(12) : error 001: expected token: ";", but found "]"
C:\Users\PC\Desktop\Diverse-Roleplay-master\gamemodes\AccountSetup.pwn(12) : error 029: invalid expression, assumed zero
C:\Users\PC\Desktop\Diverse-Roleplay-master\gamemodes\AccountSetup.pwn(12) : fatal error 107: too many error messages on one line`

**Comment by Sparke00** [comment]
It looks like you're trying to compile AccountSetup.pwn, and not Compile.pwn. Have you edited anything inside of the script prior to compiling compile.pwn (if you even are)

**Comment by Sparke00** [comment]
Also it looks as if you you may have removed #includle <a_samp>

**Comment by nicholasx5** [comment]
I haven't touched anything on the script and I go and compile accountsetup to change the name and it's gives me errors.

**Comment by Sparke00** [comment]
You're supposed to compile, compile.pwn not accountsetup.pwn

**Comment by nicholasx5** [comment]
I did compile it. I'm trying to edit the accountsetup to change the name inside it but it's giving me errors.

**Comment by Sparke00** [comment]
You save the accountsetup.pwn then you go compile "compile.pwn" then it'll compile accountsetup.pwn.

**Comment by nicholasx5** [comment]
Oh my god. Thank you dude. Sorry I'm new to scripting.

**Comment by nicholasx5** [comment]
Is there anything else that requires to be edit & saved and then compile "compile.pwn" to compile it?

**Comment by Sparke00** [comment]
Nope, and no problem.
